######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 22:03:23 2010
######################################################################

QT+=network
TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/ftpclient.h src/ftpclientwindow.h
FORMS += src/ftpclientwindow.ui
SOURCES += src/ftpclient.cpp src/ftpclientwindow.cpp src/main.cpp
RESOURCES += src/ftp.qrc
