#############################################################################
# Makefile for building: ftpclient
# Generated by qmake (2.01a) (Qt 4.4.3) on: ?? ??? 1 22:03:25 2010
# Project:  ftpclient.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.4.3/bin/qmake -unix -o Makefile ftpclient.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.3/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.4.3/include/QtCore -I/usr/local/Trolltech/Qt-4.4.3/include/QtCore -I/usr/local/Trolltech/Qt-4.4.3/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.3/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.3/include/QtGui -I/usr/local/Trolltech/Qt-4.4.3/include/QtGui -I/usr/local/Trolltech/Qt-4.4.3/include -I. -Isrc -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.4.3/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.3/lib -lQtGui -L/usr/local/Trolltech/Qt-4.4.3/lib -L/usr/X11R6/lib -pthread -pthread -pthread -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.4.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ftpclient.cpp \
		src/ftpclientwindow.cpp \
		src/main.cpp moc_ftpclient.cpp \
		moc_ftpclientwindow.cpp \
		qrc_ftp.cpp
OBJECTS       = ftpclient.o \
		ftpclientwindow.o \
		main.o \
		moc_ftpclient.o \
		moc_ftpclientwindow.o \
		qrc_ftp.o
DIST          = /usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf \
		ftpclient.pro
QMAKE_TARGET  = ftpclient
DESTDIR       = 
TARGET        = ftpclient

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ftpclientwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ftpclient.pro  /usr/local/Trolltech/Qt-4.4.3/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.4.3/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile ftpclient.pro
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.3/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.4.3/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile ftpclient.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ftpclient1.0.0 || $(MKDIR) .tmp/ftpclient1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ftpclient1.0.0/ && $(COPY_FILE) --parents src/ftpclient.h src/ftpclientwindow.h .tmp/ftpclient1.0.0/ && $(COPY_FILE) --parents src/ftp.qrc .tmp/ftpclient1.0.0/ && $(COPY_FILE) --parents src/ftpclient.cpp src/ftpclientwindow.cpp src/main.cpp .tmp/ftpclient1.0.0/ && $(COPY_FILE) --parents src/ftpclientwindow.ui .tmp/ftpclient1.0.0/ && (cd `dirname .tmp/ftpclient1.0.0` && $(TAR) ftpclient1.0.0.tar ftpclient1.0.0 && $(COMPRESS) ftpclient1.0.0.tar) && $(MOVE) `dirname .tmp/ftpclient1.0.0`/ftpclient1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ftpclient1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ftpclient.cpp moc_ftpclientwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ftpclient.cpp moc_ftpclientwindow.cpp
moc_ftpclient.cpp: src/ftpclient.h
	/usr/local/Trolltech/Qt-4.4.3/bin/moc $(DEFINES) $(INCPATH) src/ftpclient.h -o moc_ftpclient.cpp

moc_ftpclientwindow.cpp: src/ui_ftpclientwindow.h \
		src/ftpclient.h \
		src/ftpclientwindow.h
	/usr/local/Trolltech/Qt-4.4.3/bin/moc $(DEFINES) $(INCPATH) src/ftpclientwindow.h -o moc_ftpclientwindow.cpp

compiler_rcc_make_all: qrc_ftp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ftp.cpp
qrc_ftp.cpp: src/ftp.qrc \
		src/images/dir.png \
		src/images/file.png \
		src/images/cdtoparent.png
	/usr/local/Trolltech/Qt-4.4.3/bin/rcc -name ftp src/ftp.qrc -o qrc_ftp.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ftpclientwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ftpclientwindow.h
ui_ftpclientwindow.h: src/ftpclientwindow.ui
	/usr/local/Trolltech/Qt-4.4.3/bin/uic src/ftpclientwindow.ui -o ui_ftpclientwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

ftpclient.o: src/ftpclient.cpp src/ftpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ftpclient.o src/ftpclient.cpp

ftpclientwindow.o: src/ftpclientwindow.cpp src/ftpclientwindow.h \
		src/ui_ftpclientwindow.h \
		src/ftpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ftpclientwindow.o src/ftpclientwindow.cpp

main.o: src/main.cpp src/ftpclientwindow.h \
		src/ui_ftpclientwindow.h \
		src/ftpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

moc_ftpclient.o: moc_ftpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ftpclient.o moc_ftpclient.cpp

moc_ftpclientwindow.o: moc_ftpclientwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ftpclientwindow.o moc_ftpclientwindow.cpp

qrc_ftp.o: qrc_ftp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ftp.o qrc_ftp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

